### ISSUE TITLE
bosh director deploy on OpenStack failed with an error ：Waiting for instance 'bosh/0' to be running... Failed

### ISSUE THREAD

**Issue by mllives** [cloudfoundry/bosh-micro-cli#132]
when i performed a deployment command on controller node, it will failed at creating bosh agent in vm bosh/0. I found it was for the reason that bosh/0 cannot running,its booting process suspend at "boot from a hard disk,grubbed...". I change the value of virt_type in compute node from kvm to qemu, i can setup a bosh agent in bosh/0. But at last it still failed at "Waiting for instance 'bosh/0' to be running... Failed" after a long time compilation. what's wrong with it? i am very confused about it ? I am really appreciated it if you can help me out.

**Comment by dpb587-pivotal** [comment]
Closing this issue and archiving this repository - active development continues in [cloudfoundry/bosh-cli](https://github.com/cloudfoundry/bosh-cli). If you are still experiencing issues, please create a new issue with details there.

**Comment by mllives** [comment]
ok，thanks a lot!
